dist: focal

language: python

python:
- 3.6.9
- 3.7.9
- 3.8.7
- 3.9.1

git:
  depth: 3
  quiet: true

install: pip install .[tests]

script: pytest -v -s tests/

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  username: "__token__"
  password:
    secure: "rDij0CFIC9zkyzQJnHmJyG/TeMVqYHAtkMbISihd0gf2xeN/q7QKpSQ4Rqq8S6ZA4CnNeAQ8Qw9vf0wLQcEoS24TK7g4ArZB5qfOhm4NzDiAta/QdkvRGlO+jQNOKX0+1G72xAFL7G8ji8Xn26+hzQOET5JAs4TPELU38AZ4M+qZAI3LrKXkNyhsTRBZIpAbIh8Tf+mosw8++f1+Q6GWieNIkusS/F4R9/Gk2e5nm/WLTuLueJ5vxr2GwQjbCElEyEvBzcJi9LEf/OEI2lLqUBW+44HQdkY4y1+8DGcBviZrfPK2tUNdzh6Ot9Oe1aZVaX/1xkJr+FiKDMBZT12y+FKu4FUgFzVaIpGEl2NkCQk26hCrvPet60dOKsMAFKjRzQp2APSyNcKaoO4VOA1Rc1TIz8ku0rFZNWt2WBMVMXWmxG6VzStwrHcHO+vxdlVl7k3sy+BrX1WBsR38Ivj5oCjxUaA1y1uj6ikdS9xsSMT+cmSG50BX/1ErwlnIsP+weK0ML4xfcVQDHxpJZaV19hReDmhPhZsKNqsstpNbxZvQDuCxRgEu/6Pr7t29SqF79z2T5jFiCUOdIRfdHs6oqb4MNz56Wg8NyIRvj9VWMPmSGQwQVTlqFr4OAqIjx6xgRFP3GIHsDkNzE0En+zkwqzvL++Ql81AC4tO+ItUh2LY="
  on:
    tags: true
    repo: Helow19274/aiogTTS
    python: 3.9.1
